spring:
  datasource:
    url: jdbc:h2:mem:openciv-test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/V7__add_shedlock.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false

  h2:
    console:
      enabled: false

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
