-- Add consensus_coins and spy_bots to civilizations
ALTER TABLE civilizations ADD COLUMN IF NOT EXISTS consensus_coins DOUBLE PRECISION DEFAULT 100.0;
ALTER TABLE civilizations ADD COLUMN IF NOT EXISTS spy_bots_priority INTEGER DEFAULT 0;

-- Create espionage_operations table
CREATE TABLE IF NOT EXISTS espionage_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_id BIGINT REFERENCES civilizations(id),
    target_id BIGINT REFERENCES civilizations(id),
    type VARCHAR(50) NOT NULL,
    spy_bots_count INTEGER NOT NULL,
    risk_level DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    ticks_remaining INTEGER NOT NULL
);
