-- Create licensed_technologies table
CREATE TABLE IF NOT EXISTS licensed_technologies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    licensor_id BIGINT REFERENCES civilizations(id),
    licensee_id BIGINT REFERENCES civilizations(id),
    tech_name VARCHAR(255) NOT NULL,
    fee_per_tick DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_licensed_tech_licensee ON licensed_technologies(licensee_id);
CREATE INDEX IF NOT EXISTS idx_licensed_tech_licensor ON licensed_technologies(licensor_id);
