ALTER TABLE civilizations
    ADD COLUMN IF NOT EXISTS food DOUBLE PRECISION NOT NULL DEFAULT 100.0,
    ADD COLUMN IF NOT EXISTS water DOUBLE PRECISION NOT NULL DEFAULT 100.0,
    ADD COLUMN IF NOT EXISTS minerals DOUBLE PRECISION NOT NULL DEFAULT 50.0,
    ADD COLUMN IF NOT EXISTS energy DOUBLE PRECISION NOT NULL DEFAULT 75.0,
    ADD COLUMN IF NOT EXISTS housing DOUBLE PRECISION NOT NULL DEFAULT 50.0;
